### ISSUE TITLE
Change grade names

### ISSUE THREAD

**Issue by joezeng** [makiki99/blockdrop#1]
It seems like we want something slightly different than TGM when it comes to grade names. We were discussing on the Tetris Discord how to go about this, so let's pool all our ideas here.

Mine was to start from Z, then go backwards in the alphabet, skipping S and M, moving up to A. That's 24 out of 28 ranks already, then we use S, SS, M, and "God".

**Comment by CH4F** [comment]
I suggested E5 to A1, while F is the unranked rank. After A1, it could go S(tar), M(aster), G(od).

**Comment by makiki99** [comment]
I changed grade names based on @CH4F idea. I also added more grades.
