### ISSUE TITLE
Line ARE is too long

### ISSUE THREAD

**Issue by joezeng** [makiki99/blockdrop#3]
When you clear a line, the delay before the next piece comes is twice as long.

The only reason they do this in the original TGM games is because the blocks above cleared lines don't fall down immediately — there's a 40-frame delay when the lines are cleared.

You don't have this delay implemented (the line clear animation is only a few frames long and the blocks fall instantly after that) so it's jarring to have the block delay be different when a line is being cleared.

**Comment by makiki99** [comment]
Lowered the starting lock delay to 22 frames. I don't want to lower it too heavily, because it is important part of the game.
